export const INDIAN_LANGUAGES = [
    { code: 'hi', name: 'Hindi' },
    { code: 'mr', name: 'Marathi' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'bn', name: 'Bengali' },
    { code: 'ta', name: 'Tamil' },
    { code: 'te', name: 'Telugu' },
    { code: 'kn', name: 'Kannada' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'pa', name: 'Punjabi' },
    { code: 'ur', name: 'Urdu' },
    { code: 'or', name: 'Odia' },
    { code: 'as', name: 'Assamese' },
    { code: 'ks', name: 'Kashmiri' },
    { code: 'kok', name: 'Konkani' },
    { code: 'mai', name: 'Maithili' },
    { code: 'mni', name: 'Manipuri' },
    { code: 'ne', name: 'Nepali' },
    { code: 'sa', name: 'Sanskrit' },
    { code: 'sd', name: 'Sindhi' },
    { code: 'sat', name: 'Santali' },
    { code: 'brx', name: 'Bodo' },
    { code: 'doi', name: 'Dogri' },
    { code: 'en', name: 'English' },
];

export const GRADE_LEVELS = [
    { value: '6', label: 'Class 6' },
    { value: '7', label: 'Class 7' },
    { value: '8', label: 'Class 8' },
    { value: '9', label: 'Class 9' },
    { value: '10', label: 'Class 10' },
    { value: '11', label: 'Class 11' },
    { value: '12', label: 'Class 12' },
    { value: 'Undergrad', label: 'Undergraduate' },
    { value: 'Grad', label: 'Graduate' },
];
